BudgetPlanner/Models/BudgetAccount.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BudgetPlanner.Models
{
    public class BudgetAccount
    {
        public int Id { get; set; }
        public int HouseholdId { get; set; }
        public string Name { get; set; }
        public decimal Balance { get; set; }
        public decimal ReconciledBalance { get; set; }

        public virtual Household Household { get; set; }

        public virtual ICollection<Transaction> Transactions { get; set; }

        public BudgetAccount()
        {
            Transactions = new HashSet<Transaction>();
        }
    }
}

BudgetPlanner/Controllers/BudgetAccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using BudgetPlanner.Models;

namespace BudgetPlanner.Controllers
{   
    [RequireHousehold]
    public class BudgetAccountsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BudgetAccounts
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var hhId = int.Parse(User.Identity.GetHouseholdId());

            var budgetAccounts = db.BudgetAccounts.Include(b => b.Household);
            ViewBag.Household = db.Household.First(h => h.Id == hhId).Name;

            return View(budgetAccounts.ToList());
        }

        // GET: BudgetAccounts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BudgetAccount budgetAccount = db.BudgetAccounts.Find(id);
            if (budgetAccount == null)
            {
                return HttpNotFound();
            }
            return View(budgetAccount);
        }

        // GET: BudgetAccounts/Create
        public ActionResult Create()
        {
            var userId = User.Identity.GetUserId();
            var hhId = int.Parse(User.Identity.GetHouseholdId());

            ViewBag.Household = db.Household.First(h => h.Id == hhId).Name;
            return View();
        }

        // POST: BudgetAccounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Balance,ReconciledBalance")] BudgetAccount budgetAccount)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();

                budgetAccount.HouseholdId = int.Parse(User.Identity.GetHouseholdId());

                db.BudgetAccounts.Add(budgetAccount);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.HouseholdId = new SelectList(db.Household, "Id", "Name", budgetAccount.HouseholdId);
            return View(budgetAccount);
        }

        // GET: BudgetAccounts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BudgetAccount budgetAccount = db.BudgetAccounts.Find(id);
            if (budgetAccount == null)
            {
                return HttpNotFound();
            }

            var userId = User.Identity.GetUserId();
            var hhId = int.Parse(User.Identity.GetHouseholdId());

            ViewBag.Household = db.Household.First(h => h.Id == hhId).Name;
            return View(budgetAccount);
        }

        // POST: BudgetAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HouseholdId,Name,Balance,ReconciledBalance")] BudgetAccount budgetAccount)
        {
            if (ModelState.IsValid)
            {
                db.Entry(budgetAccount).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HouseholdId = new SelectList(db.Household, "Id", "Name", budgetAccount.HouseholdId);
            return View(budgetAccount);
        }

        // GET: BudgetAccounts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BudgetAccount budgetAccount = db.BudgetAccounts.Find(id);
            if (budgetAccount == null)
            {
                return HttpNotFound();
            }
            return View(budgetAccount);
        }

        // POST: BudgetAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            // Delete Transactions
            //Transaction transactions = db.Transactions.SelectMany(t=> t.AccountId)
            // Delete account
            BudgetAccount budgetAccount = db.BudgetAccounts.Find(id);
            db.BudgetAccounts.Remove(budgetAccount);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BudgetPlanner/Views/BudgetAccounts/Create.cshtml
@model BudgetPlanner.Models.BudgetAccount

@{
    ViewBag.Title = "Create Account";
}

    <br />
    <br />
    <div class="col-md-12">
        <div class="col-md-10">
            <div class="panel">
                <div class="panel-heading">
                    <div class="col-md-12">
                        <div class="col-md-pull-1">
                            <div class="btn pull-left"><a href="@Url.Action("Index", "BudgetAccounts")" class="glyphicon glyphicon-hand-left" style="font-size: 16px"> </a></div>
                        </div>
                        <div class="col-md-5">
                            <h4>
                                @ViewBag.Household Household
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="col-md-12">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", autofocus="autofocus" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Balance, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Balance, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Balance, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.ReconciledBalance, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ReconciledBalance, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ReconciledBalance, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }                        
                    </div>
                </div> <!-- panel body -->
            </div><!--panel-->
        </div><!--col-md-10-->
    </div><!-- col-md-12 -->



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BudgetPlanner/Views/BudgetAccounts/Delete.cshtml
@model BudgetPlanner.Models.BudgetAccount

@{
    ViewBag.Title = "Delete Account";
}

<br />
<br />
<div class="col-md-12">
    <div class="col-md-10">
        <div class="panel">
            <div class="panel-heading">
                <div class="col-md-12">
                    <div class="col-md-pull-1">
                        <div class="btn pull-left"><a href="@Url.Action("Index", "BudgetAccounts")" class="glyphicon glyphicon-hand-left" style="font-size: 16px"> </a></div>
                    </div>
                    <div class="col-md-5">
                        <h4>
                            Are you sure you want to delete this?
                        </h4>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <div class="col-md-12">

                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Household.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Household.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Balance)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Balance)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.ReconciledBalance)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.ReconciledBalance)
                        </dd>

                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-default" />                            
                        </div>
                    }
                    <br />
                </div>
            </div> <!-- panel body -->
        </div><!--col-md-10-->
    </div><!--col-md-12-->
</div><!-- /row -->

BudgetPlanner/Views/BudgetAccounts/Details.cshtml
@model BudgetPlanner.Models.BudgetAccount

@{
    ViewBag.Title = "Account Details";
}

<h2>Details</h2>

<div>
    <h4>BudgetAccount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Household.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Household.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReconciledBalance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReconciledBalance)
        </dd>

    </dl>
</div>
<p>
    <div>
        <div class="btn pull-left"><a href="@Url.Action("Edit", "BudgetAccounts", new { id = Model.Id })" class="glyphicon glyphicon-pencil" style="font-size: 16px"> </a></div>
    </div>
    @@*Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")*@
</p>
<p>
    <div class="btn pull-left"><a href="@Url.Action("Index", "BudgetAccounts")" class="glyphicon glyphicon-hand-left" style="font-size: 16px"> </a></div>
</p>

BudgetPlanner/Views/BudgetAccounts/Edit.cshtml
@model BudgetPlanner.Models.BudgetAccount

@{
    ViewBag.Title = "Edit Account";
}

    <br />
    <br />
    <div class="col-md-12">
        <div class="col-md-10">
            <div class="panel">
                <div class="panel-heading">
                    <div class="col-md-12">
                        <div class="col-md-5">
                            <h4>
                                @ViewBag.Household Household
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="col-md-12">

                       @using (Html.BeginForm())
                       {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", autofocus = "autofocus" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Balance, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Balance, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Balance, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ReconciledBalance, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ReconciledBalance, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ReconciledBalance, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                       }

                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>
                    </div>
                </div> <!-- panel body -->
            </div><!--panel-->
        </div><!--col-md-10-->
    </div><!-- col-md-12 -->
@*</div>*@ <!-- /container -->

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BudgetPlanner/Views/BudgetAccounts/Index.cshtml
@model IEnumerable<BudgetPlanner.Models.BudgetAccount>

@{
    ViewBag.Title = "Account Index";
}

@*<link href="~/Content/Block/main.css" rel="stylesheet" />*@

@*<div class="container">*@
    <br />
    <br />
<div class="row">
    <div class="col-md-12">
        @*<div class="col-md-10">*@
        <div class="panel">
            <div class="panel-heading">
                <div class="btn pull-left"><a href="@Url.Action("Create", "BudgetAccounts")" class="glyphicon glyphicon-plus"> </a></div>
                <div class="text-center">
                    <h4>
                        @ViewBag.Household Household Accounts
                    </h4>
                </div>
            </div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Balance)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ReconciledBalance)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <a href="@Url.Action("Delete","BudgetAccounts",new{id=item.Id})" class="glyphicon glyphicon-trash"> </a>
                                </td>
                                <td>
                                    <a href="@Url.RouteUrl("TransactionIndex", new { acctId = item.Id })"> @Html.DisplayFor(modelItem => item.Name) </a>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Balance)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ReconciledBalance)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div> <!-- panel body -->
        </div><!--panel-->
        @*</div>*@<!--col-md-10-->
    </div><!-- col-md-12 -->
</div>
    
@*</div>*@ <!-- /container -->