BudgetPlanner/Models/BudgetItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BudgetPlanner.Models
{
    public class BudgetItem
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int HouseholdId { get; set; }
        public int? CategoryId { get; set; }
        public decimal Amount { get; set; }
        public int Frequency { get; set; }

        public virtual Category Category { get; set; }
        public virtual Household Household { get; set; }
    }
}

BudgetPlanner/Controllers/BudgetItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using BudgetPlanner.Models;

namespace BudgetPlanner.Controllers
{

    [RequireHousehold]
    public class BudgetItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BudgetItems
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var hhId = int.Parse(User.Identity.GetHouseholdId());

            var budgetAccounts = db.BudgetAccounts.Include(b => b.Household);
            ViewBag.HhName = db.Household.FirstOrDefault(h=> h.Id == hhId).Name;

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            var budgetItems = db.BudgetItems.Include(b => b.Category).Include(b => b.Household);
            return View(budgetItems.ToList());
        }

        // GET: BudgetItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BudgetItem budgetItem = db.BudgetItems.Find(id);
            if (budgetItem == null)
            {
                return HttpNotFound();
            }
            return View(budgetItem);
        }

        // GET: BudgetItems/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            //ViewBag.HouseholdId = new SelectList(db.Household, "Id", "Name");
            return View();
        }

        // POST: BudgetItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CategoryId,Description,Amount,Frequency")] BudgetItem budgetItem)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                
                budgetItem.HouseholdId = int.Parse(User.Identity.GetHouseholdId());

                db.BudgetItems.Add(budgetItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", budgetItem.CategoryId);
            //ViewBag.HouseholdId = new SelectList(db.Household, "Id", "Name", budgetItem.HouseholdId);
            return View(budgetItem);
        }

        // GET: BudgetItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BudgetItem budgetItem = db.BudgetItems.Find(id);
            if (budgetItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", budgetItem.CategoryId);
            //ViewBag.HouseholdId = new SelectList(db.Household, "Id", "Name", budgetItem.HouseholdId);
            return View(budgetItem);
        }

        // POST: BudgetItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CategoryId,Description,Amount,Frequency")] BudgetItem budgetItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(budgetItem).State = EntityState.Modified;
                db.Entry(budgetItem).Property(p => p.HouseholdId).IsModified = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", budgetItem.CategoryId);
            //ViewBag.HouseholdId = new SelectList(db.Household, "Id", "Name", budgetItem.HouseholdId);
            return View(budgetItem);
        }

        // GET: BudgetItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BudgetItem budgetItem = db.BudgetItems.Find(id);
            if (budgetItem == null)
            {
                return HttpNotFound();
            }
            return View(budgetItem);
        }

        // POST: BudgetItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BudgetItem budgetItem = db.BudgetItems.Find(id);
            db.BudgetItems.Remove(budgetItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BudgetPlanner/Views/BudgetItems/Create.cshtml
@model BudgetPlanner.Models.BudgetItem

@{
    ViewBag.Title = "Create Budget Item";
}

@*<div class="container">*@
    <br />
    <br />
    <div class="col-md-12">
        <div class="col-md-10">
            <div class="panel">
                <div class="panel-heading">
                    <div class="col-md-12">
                        <div class="col-md-pull-1">
                            <div class="btn pull-left"><a href="@Url.Action("Index", "BudgetItems")" class="glyphicon glyphicon-hand-left" style="font-size: 16px"> </a></div>
                        </div>
                        <div class="col-md-5">
                            <h4>
                                New Budget Item
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="col-md-12">
                        @using (Html.BeginForm("Create", "BudgetItems", FormMethod.Post,
                            new { encType = "multipart/form-data", name = "myform" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-group">
                                    <div class="col-md-2">
                                        @Html.Label("Category")
                                    </div>
                                    <div class="col-md-6">
                                        @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-2">
                                        @Html.Label("Description")
                                    </div>
                                    <div class="col-md-6">
                                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", autofocus = "autofocus" } })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-2">
                                        @Html.Label("Amount")
                                    </div>
                                    <div class="col-md-6">
                                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-2">
                                        @Html.Label("Frequency")
                                    </div>
                                    <div class="col-md-6">
                                        @Html.EditorFor(model => model.Frequency)
                                        @Html.ValidationMessageFor(model => model.Frequency, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <div class="panel-footer">

                </div>
            </div>
        </div>
    </div>
@*</div>*@


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BudgetPlanner/Views/BudgetItems/Delete.cshtml
@model BudgetPlanner.Models.BudgetItem

@{
    ViewBag.Title = "Delete Budget Item";
}

<br />
<br />
<div class="col-md-12">
    <div class="col-md-10">
        <div class="panel">
            <div class="panel-heading">
                <div class="col-md-12">
                    <div class="col-md-pull-1">
                        <div class="btn pull-left"><a href="@Url.Action("Index", "BudgetItems")" class="glyphicon glyphicon-hand-left" style="font-size: 16px"> </a></div>
                    </div>
                    <div class="col-md-5">
                        <h4>
                            Are you sure you want to delete this?
                        </h4>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <div class="col-md-12">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Category.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Category.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Household.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Household.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Amount)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Amount)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Frequency)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Frequency)
                        </dd>

                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-default" />
                        </div>
                    }
                    <br />
                </div>
            </div> <!-- panel body -->
        </div><!--col-md-10-->
    </div><!--col-md-12-->
</div><!-- /row -->

BudgetPlanner/Views/BudgetItems/Edit.cshtml
@model BudgetPlanner.Models.BudgetItem

@{
    ViewBag.Title = "Edit Budget Item";
}

<br />
<br />
<div class="col-md-12">
    <div class="col-md-10">
        <div class="panel">
            <div class="panel-heading">
                <div class="col-md-12">
                    <div class="col-md-pull-1">
                        <div class="btn pull-left"><a href="@Url.Action("Index", "BudgetItems")" class="glyphicon glyphicon-hand-left" style="font-size: 16px"> </a></div>
                    </div>
                    <div class="col-md-5">
                        <h4>
                            @ViewBag.Household Household
                        </h4>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <div class="col-md-12">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.HouseholdId)

                            <div class="form-group">
                                @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", autofocus = "autofocus" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Frequency, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Frequency)
                                    @Html.ValidationMessageFor(model => model.Frequency, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div> <!-- panel body -->
        </div><!--col-md-10-->
    </div><!--col-md-12-->
</div><!-- /row -->

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BudgetPlanner/Views/BudgetItems/Index.cshtml
@using BudgetPlanner.Models;

@model IEnumerable<BudgetPlanner.Models.BudgetItem>

@{
    ViewBag.Title = "Budget Item Index";
}


    <br />
    <br />
<div class="row">
    <div class="col-md-12">        
        <div class="row"> 
            <div class="col-md-6">
                <h4 style="color: white">
                    @ViewBag.HhName
                    Household Budget
                </h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="panel">
                    <div class="panel-heading">
                        <div class="btn pull-left"><a href="@Url.Action("Create","BudgetItems")" class="glyphicon glyphicon-plus"> </a></div>
                        <div class="text-left">
                            <h4>Income</h4>
                        </div>
                    </div>
                    <div class="panel-body">
                        <table class="table">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Description)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Category.Name)
                                </th>                                
                                <th>
                                    @Html.DisplayNameFor(model => model.Amount)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Frequency)
                                </th>
                                <th></th>
                            </tr>

                            @foreach (var item in Model.Where(b=> b.Category.Income == true))
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Category.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Amount)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Frequency)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit","BudgetItems",new{id=item.Id})" class="glyphicon glyphicon-pencil"> </a>
                                        <a href="@Url.Action("Delete","BudgetItems",new{id=item.Id})" class="glyphicon glyphicon-trash"> </a>
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>          
            </div>
            <div class="col-md-6">
                <div class="panel">
                    <div class="panel-heading">
                        <div class="btn pull-left"><a href="@Url.Action("Create","BudgetItems")" class="glyphicon glyphicon-plus"> </a></div>
                        <div class="text-left">
                            <h4>Expenses</h4>
                        </div>
                    </div>
                    <div class="panel-body">
                        <table class="table">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Description)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Category.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Amount)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Frequency)
                                </th>
                                <th></th>
                            </tr>

                            @foreach (var item in Model.Where(b => b.Category.Expense == true))
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Category.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Amount)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Frequency)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit","BudgetItems",new{id=item.Id})" class="glyphicon glyphicon-pencil"> </a>
                                        <a href="@Url.Action("Delete","BudgetItems",new{id=item.Id})" class="glyphicon glyphicon-trash"> </a>
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
            </div>
        </div>       
    </div>
</div>